#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 || $# -gt 2 || ! "$1" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ || ( $# -eq 2 && "$2" != --check ) ]]; then
  echo "usage: $0 <vX.Y.Z> [--check]" >&2
  exit 2
fi
version=$1
root=$(cd "$(dirname "$0")/.." && pwd)
pins="$root/plugins/guardrails/pins.txt"
for tool in cosign curl jq tar shasum; do
  command -v "$tool" >/dev/null || { echo "$tool is required" >&2; exit 1; }
done
scratch=$(mktemp -d)
candidate=""
trap 'rm -rf "$scratch"; if [[ -n "$candidate" ]]; then rm -f "$candidate"; fi' EXIT
base="https://dneaqnz3vqe4a.cloudfront.net/guardrails/$version"
identity="https://github.com/KonvuTeam/konvu-guardrails/.github/workflows/release-guardrails.yml@refs/tags/$version"
fetch() {
  curl --proto '=https' --tlsv1.2 --fail --silent --show-error --location \
    --connect-timeout 15 --max-time 300 "$base/$1" --output "$scratch/$1"
}
verify() {
  cosign verify-blob "$scratch/$1" --bundle "$scratch/$1.bundle" \
    --certificate-identity "$identity" \
    --certificate-oidc-issuer https://token.actions.githubusercontent.com >&2
}
fetch guardrails-release.json
fetch guardrails-release.json.bundle
verify guardrails-release.json
manifest="$scratch/guardrails-release.json"
jq -e --arg version "$version" '
  .schema_version == 1 and .version == $version and
  .source.repository == "KonvuTeam/konvu-guardrails" and
  .source.workflow == ".github/workflows/release-guardrails.yml" and
  (.source.commit | test("^[0-9a-f]{40}$"))
' "$manifest" >/dev/null
fetch checksums.txt
{
  echo '# Pinned guardrails CLI release. The plugin installs only these bytes.'
  echo '# Generated by scripts/pin-cli.sh after verifying the release signature and every archive.'
  echo '# Format: version <tag>, then <target triple> <archive sha256> <guardrails binary sha256>.'
  echo "version $version"
} >"$scratch/pins.txt"
for target in aarch64-apple-darwin x86_64-apple-darwin aarch64-unknown-linux-gnu x86_64-unknown-linux-gnu; do
  archive="guardrails-cli-$target.tar.xz"
  read -r archive_hash binary_hash < <(jq -er --arg target "$target" --arg archive "$archive" '
    .artifacts[$target] |
    select(.archive.name == $archive) |
    [.archive.sha256, .binaries.guardrails.sha256] |
    select(all(.[]; type == "string" and test("^[0-9a-f]{64}$"))) | @tsv
  ' "$manifest")
  fetch "$archive"
  fetch "$archive.bundle"
  verify "$archive"
  actual=$(shasum -a 256 "$scratch/$archive" | awk '{print $1}')
  [[ "$actual" == "$archive_hash" ]]
  listed=$(awk -v name="$archive" '$2 == name {print $1}' "$scratch/checksums.txt")
  [[ "$listed" == "$archive_hash" ]]
  member=$(tar -tf "$scratch/$archive" | awk -F/ '$NF == "guardrails" {print}')
  [[ -n "$member" && "$member" != *$'\n'* ]]
  actual=$(tar -xOf "$scratch/$archive" "$member" | shasum -a 256 | awk '{print $1}')
  [[ "$actual" == "$binary_hash" ]]
  printf '%s %s %s\n' "$target" "$archive_hash" "$binary_hash" >>"$scratch/pins.txt"
done
if [[ ${2:-} == --check ]]; then
  diff -u <(sed '/^#/d; /^$/d' "$pins") <(sed '/^#/d; /^$/d' "$scratch/pins.txt")
else
  candidate=$(mktemp "$pins.XXXXXX")
  cp "$scratch/pins.txt" "$candidate"
  chmod 0644 "$candidate"
  mv "$candidate" "$pins"
fi
